---
title: Errore del compilatore CS0156
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: f755172711f7a09bcbdae518fdcb82aca58cad20
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs0156"></a>Errore del compilatore CS0156
L'utilizzo dell'istruzione throw senza argomenti non è consentito in una clausola finally annidata all'interno della clausola catch di inclusione più vicina  
  
 Un'istruzione [throw](../../csharp/language-reference/keywords/throw.md) senza parametri può essere usata solo in una clausola **catch** che non accetta parametri.  
  
 Per ulteriori informazioni, vedere [istruzioni di gestione delle eccezioni](../../csharp/language-reference/keywords/exception-handling-statements.md) e [eccezioni e gestione delle eccezioni](../../csharp/programming-guide/exceptions/index.md).  
  
 L'esempio seguente genera l'errore CS0156:  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
