---
title: "&#39; Catch &#39; non può trovarsi all'esterno di un &#39; Provare a &#39; istruzione"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords: BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
caps.latest.revision: "7"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 62502b364e8609ba66e59507554029e67b563269
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39; Catch &#39; non può trovarsi all'esterno di un &#39; Provare a &#39; istruzione
`Catch` deve figurare all'interno di un blocco di istruzioni `Try...Catch...Finally` . Nel blocco `Catch` è presente un'istruzione `Try` non necessaria oppure l'istruzione `Catch` si trova al di fuori dei limiti del blocco `Try` corrispondente.  
  
 **ID errore:** BC30380  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1.  Eliminare l'istruzione `Catch` se non è necessaria oppure inserirla all'interno di un blocco di istruzioni `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Vedere anche  
 [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Gestione delle eccezioni Panoramica per Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)
