---
title: "&#39;Genera&#39; l'istruzione non può omettere l'operando all'esterno di un &#39;Catch&#39; istruzione o all'interno un &#39;infine&#39; istruzione"
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: e263e98cce568deb5597c4b03c1b8b6534d6b0d3
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 05/04/2018
ms.locfileid: "33618355"
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a><span data-ttu-id="a8050-102">&#39;Genera&#39; l'istruzione non può omettere l'operando all'esterno di un &#39;Catch&#39; istruzione o all'interno un &#39;infine&#39; istruzione</span><span class="sxs-lookup"><span data-stu-id="a8050-102">&#39;Throw&#39; statement cannot omit operand outside a &#39;Catch&#39; statement or inside a &#39;Finally&#39; statement</span></span>
<span data-ttu-id="a8050-103">Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.</span><span class="sxs-lookup"><span data-stu-id="a8050-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="a8050-104">**ID errore:** BC30666</span><span class="sxs-lookup"><span data-stu-id="a8050-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="a8050-105">Per correggere l'errore</span><span class="sxs-lookup"><span data-stu-id="a8050-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="a8050-106">Specificare il nome di un oggetto eccezione derivato da `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="a8050-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="a8050-107">Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .</span><span class="sxs-lookup"><span data-stu-id="a8050-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="a8050-108">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="a8050-108">See Also</span></span>  
 [<span data-ttu-id="a8050-109">Istruzione Throw</span><span class="sxs-lookup"><span data-stu-id="a8050-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)  
 [<span data-ttu-id="a8050-110">Istruzione Try...Catch...Finally</span><span class="sxs-lookup"><span data-stu-id="a8050-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [<span data-ttu-id="a8050-111">Classe di eccezione in Visual Basic</span><span class="sxs-lookup"><span data-stu-id="a8050-111">Exception Class in Visual Basic</span></span>](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [<span data-ttu-id="a8050-112">Eccezioni e gestione degli errori in Visual Basic</span><span class="sxs-lookup"><span data-stu-id="a8050-112">Exception and Error Handling in Visual Basic</span></span>](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
